import { ThemeId } from "./types";

export type StudioLabelKey =
  | "brand"
  | "status"
  | "overview"
  | "posts"
  | "create_post"
  | "publications"
  | "appearance"
  | "notifications"
  | "profile"
  | "settings"
  | "logout"
  | "theme"
  | "layout"
  | "publications_desc"
  | "appearance_desc"
  | "notifications_desc"
  | "profile_desc"
  | "new_post_btn"
  | "new_publication_btn"
  | "analytics"
  | "analytics_desc"
  | "perf_visualization"
  | "performances"
  | "loading"
  | "no_data"
  | "no_data_desc"
  | "no_results"
  | "traffic_title"
  | "traffic_subtitle"
  | "delete_title"
  | "delete_desc"
  | "delete_success"
  | "create_site_title"
  | "site_name_label"
  | "site_name_placeholder"
  | "site_handle_label"
  | "site_handle_desc"
  | "available"
  | "in_use"
  | "retreat"
  | "site_created_success"
  | "logo_uploaded_success"
  | "editor_back"
  | "editor_title_placeholder"
  | "editor_content_placeholder"
  | "editor_sync_synced"
  | "editor_sync_saving"
  | "editor_sync_not_synced"
  | "change_avatar"
  | "save_changes"
  | "social_networks"
  | "account_security"
  | "display_name"
  | "tagline"
  | "location"
  | "bio"
  | "profile_updated"
  | "settings_saved"
  | "profile_desc_long"
  | "account_desc_long"
  | "email_label"
  | "security_locked"
  | "table_title"
  | "table_status"
  | "table_stats"
  | "table_date"
  | "table_actions"
  | "status_published"
  | "status_draft"
  | "status_dormant"
  | "stats_views"
  | "stats_total_views"
  | "stats_30_days"
  | "stats_7_days"
  | "stats_engagement"
  | "publication_updated_success"
  | "input_active_status";

export const STUDIO_LABELS: Record<StudioLabelKey, Record<string, string>> = {
  brand: {
    default: "CONDUIT",
    sakura: "CONDUIT",
    octane: "CONDUIT",
    journal: "Journal",
    cyber: "CONDUIT.IO",
    terminal: "CONDUIT",
    techie: "OctaneBrew",
  },
  status: {
    default: "Studio Control",
    sakura: "スタジオ ターミナル",
    octane: "WORKSHOP CONTROL",
    journal: "Writing Desk (文台)",
    cyber: "UPLINK_STATUS: ACTIVE",
    terminal: "SYS_ACTIVE",
    ronin: "Shadow Command (影の司令部)",
    techie: "SYS_READY",
  },
  overview: {
    default: "Dashboard",
    sakura: "概要",
    octane: "Kernel Diagnostics",
    journal: "Dashboard (総覧)",
    cyber: "CONTROL_CENTER",
    terminal: "~/overview",
    ronin: "SHINOBI_COMMAND (指揮)",
    techie: "Overview",
  },
  posts: {
    default: "Transmissions",
    sakura: "Stories",
    octane: "Blueprints",
    journal: "Entries (日誌)",
    cyber: "SIGNALS",
    terminal: "~/transmissions",
    ronin: "CHRONICLES (戦記)",
    techie: "Posts",
  },
  create_post: {
    default: "Create",
    sakura: "Transmit",
    octane: "Ignite",
    journal: "Inscribe (記す)",
    cyber: "INIT",
    terminal: "$ vim",
    ronin: "RECORD (録)",
    techie: "CREATE",
  },
  publications: {
    default: "Publications",
    sakura: "Transmissions",
    octane: "Transmissions",
    journal: "Journals (刊行物)",
    cyber: "RELAY_STATIONS",
    terminal: "~/nodes",
    ronin: "DOMAINS (領地)",
    techie: "Publications",
  },
  appearance: {
    default: "Appearance",
    sakura: "外観",
    octane: "Refinement",
    journal: "Aesthetic (美学)",
    cyber: "VISUAL_LAYOUT",
    terminal: "~/ui",
    ronin: "ARMOR_VISAGE (装束)",
    techie: "Appearance",
  },
  notifications: {
    default: "Notifications",
    sakura: "通知",
    octane: "Alerts",
    journal: "Letters (書簡)",
    cyber: "SIGNAL_ALERTS",
    terminal: "~/alerts",
    ronin: "INTELLIGENCE (密書)",
    techie: "Notifications",
  },
  profile: {
    default: "Profile",
    sakura: "プロフィール",
    octane: "Specs",
    journal: "Author Profile (著者)",
    cyber: "IDENT_BIOS",
    terminal: "~/profile",
    ronin: "WARRIOR_PATH (経歴)",
    techie: "Profile",
  },
  settings: {
    default: "Settings",
    sakura: "設定",
    octane: "System Config",
    journal: "Preferences (設定)",
    cyber: "CORE_PARAMS",
    terminal: "~/config",
    ronin: "DOJO_RULES (掟)",
    techie: "Settings",
  },
  logout: {
    default: "Disconnect",
    sakura: "ログアウト",
    octane: "Ignition Off",
    journal: "Sign Out (退出)",
    cyber: "LOG_OFF",
    terminal: "$ exit",
    ronin: "RETIRE (引退)",
    techie: "Logout",
  },
  theme: {
    default: "Color Theme",
    sakura: "カラーテーマ",
    octane: "Varnish",
    journal: "Ink & Vellum",
    cyber: "CHROMA_SYNC",
    terminal: "XTerm-256",
    techie: "Interface Skin",
  },
  layout: {
    default: "Global Layout",
    sakura: "レイアウト",
    octane: "Chassis",
    journal: "Typography & Structure",
    cyber: "GRID_MATRIX",
    terminal: "TTY_LAYOUT",
    techie: "Chassis Logic",
  },
  publications_desc: {
    default: "Manage your active broadcast conduits and signal nodes.",
    sakura: "アクティブなブロードキャストチャネルを管理します。",
    octane: "Oversee live broadcast frequencies and architecture data.",
    journal: "Curate your collection of literary volumes and archives.",
    cyber: "Monitor active uplink streams and encrypted relay stations.",
    terminal: "# Active nodes and mount points.",
    techie: "Manage active signal nodes and broadcast parameters.",
  },
  appearance_desc: {
    default: "Customize your publication's layout and visual style.",
    sakura: "ブログのレイアウトと外観をカスタマイズします。",
    octane: "Configure chassis structure and interface skin.",
    journal: "Refine the visual ambiance and layout of your writings.",
    cyber: "Modify the ocular output and interface protocols.",
    terminal: "# Visual parameters and UI scaling.",
    techie: "Calibrate visual interface and layout architecture.",
  },
  notifications_desc: {
    default: "Manage inbound signal notifications and system alerts.",
    sakura: "着信信号の通知とシステムアラートを管理します。",
    octane: "Configure real-time diagnostic alerts and telemetry sync.",
    journal: "Manage correspondence and announcements from the desk.",
    cyber: "Adjust sensitivity for incoming packet headers and noise.",
    terminal: "# Event listeners and interrupt vectors.",
    techie: "Monitor inbound interrupts and system status alerts.",
  },
  profile_desc: {
    default: "Manage your identity and public information across the network.",
    sakura: "ネットワーク全体での身元と公開情報を管理します。",
    octane: "Calibrate your pilot identifier and social connectivity.",
    journal: "Update your author biography and social correspondence.",
    cyber: "Rewrite identifier metadata and encrypted social hooks.",
    terminal: "# User UID and social symlinks.",
    techie: "Modify user identification and metadata across the grid.",
  },
  new_post_btn: {
    default: "Create",
    sakura: "Transmit",
    octane: "Ignite",
    journal: "Inscribe",
    cyber: "INIT",
    terminal: "$ vim",
    ronin: "RECORD",
    techie: "CREATE",
  },
  new_publication_btn: {
    default: "Create",
    sakura: "Transmit",
    octane: "Ignite",
    journal: "Inscribe",
    cyber: "INIT",
    terminal: "$ mk",
    ronin: "ESTABLISH",
    techie: "INIT",
  },
  analytics: {
    default: "Analytics",
    sakura: "統計解析",
    octane: "Telemetry Stream",
    journal: "Reading Stats",
    cyber: "SYSTEM_METRICS",
    terminal: "~/analytics",
    ronin: "BATTLE_CHART",
    techie: "Telemetry",
  },
  analytics_desc: {
    default: "Summary of your channel performance.",
    sakura: "チャンネルのパフォーマンス概要を表示します。",
    octane: "Real-time telemetry and engine performance summary.",
    journal: "A summary of how your readers are engaging with your stories.",
    cyber: "Summary of your transmission throughput and signal strength.",
    terminal: "# System throughput and I/O analytics.",
    techie: "Real-time performance metrics and signal diagnostics.",
  },
  perf_visualization: {
    default: "Performance Visualization",
    sakura: "パフォーマンスの視覚化",
    octane: "Dyno Graph",
    journal: "Reader Engagement",
    cyber: "PACKET_DISTRIBUTION",
    terminal: "I/O_GRAPH",
    ronin: "SWORD_PLAY",
    techie: "Data Streams",
  },
  performances: {
    default: "Performances",
    sakura: "実績",
    octane: "Laps",
    journal: "Best Volumes",
    cyber: "SIGNAL_STRENGTH",
    terminal: "PROCESS_LOAD",
    ronin: "VICTORIES",
    techie: "Benchmarks",
  },
  loading: {
    default: "Loading...",
    sakura: "読み込み中...",
    octane: "CRANKING UP...",
    journal: "Reviewing archives...",
    cyber: "RETRIEVING_DATA_STREAM...",
    terminal: "FETCHING...",
    techie: "Processing Data...",
  },
  no_data: {
    default: "No data found.",
    sakura: "データが見つかりません。",
    octane: "ENGINE_STALLED",
    journal: "No entries recorded yet.",
    cyber: "NO_ACTIVE_SOURCE_DETECTED",
    terminal: "[EMPTY_SECTOR]",
    ronin: "RECORD_NOT_FOUND",
    techie: "Null Response",
  },
  no_data_desc: {
    default: "Your transmissions will appear here once they are initiated.",
    sakura: "ここにはまだ何もありません。",
    octane: "Your transmissions will appear here once they are initiated.",
    journal: "Your collection is currently empty in this category.",
    cyber: "EXPECTING_BROADCASTS // FREQUENCY_IDLE",
    terminal: "[NO_DATA_IN_SECTOR]",
    techie: "Awaiting source signal. Null metadata index.",
  },
  no_results: {
    default: "No results found",
    cyber: "NO_RECORDS_FOUND",
    terminal: "NULL_RECORDS_FOUND",
    techie: "NO_RECORDS_FOUND",
    sakura: "結果が見つかりませんでした",
  },
  traffic_title: {
    default: "Traffic Overview",
    sakura: "トラフィックの概要",
    octane: "Engine Telemetry",
    journal: "Reader Patterns",
    cyber: "DATA_TRAFFIC_LOG",
    terminal: "SYSTEM_I/O",
    ronin: "WAR_STRATEGY",
    techie: "Telemetry Feed",
  },
  traffic_subtitle: {
    default: "Interactions over time",
    sakura: "時間経過に伴う変化",
    octane: "Real-time diagnostics",
    journal: "Flow of the pen",
    cyber: "PACKET_THROUGHPUT",
    terminal: "KERNEL_STATS",
    ronin: "FLOW_OF_BATTLE",
    techie: "Signal oscillations",
  },
  delete_title: {
    default: "Delete this article?",
    sakura: "この記事を削除しますか？",
    octane: "Scrap Blueprint?",
    journal: "Erase Entry?",
    cyber: "TERMINATE_SIGNAL?",
    terminal: "RM_RF_FILE?",
    ronin: "ERASE_CHRONICLE?",
    techie: "Scrub file?",
  },
  delete_desc: {
    default: "This article will be permanently removed.",
    sakura: "この記事は永久に削除されます。",
    octane: "This chassis component will be recycled.",
    journal: "This entry will be burned from the journal.",
    cyber: "THIS SIGNAL WILL BE PERMANENTLY DELETED FROM THE NODE.",
    terminal: "# FILE_WILL_BE_UNLINKED_FOREVER",
    ronin: "THIS_RECORD_WILL_VANISH_FOREVER",
    techie: "This file will be permanently purged from the node.",
  },
  delete_success: {
    default: "Article deleted.",
    sakura: "記事を削除しました。",
    octane: "Scrapped.",
    journal: "Entry archived to trash.",
    cyber: "SIGNAL_TERMINATED.",
    terminal: "SUCCESS: RM_RF",
    ronin: "RECORD_ERASED.",
  },
  create_site_title: {
    default: "Create New Publication",
    sakura: "新規配信の初期化",
    octane: "Initialize Transmission",
    journal: "Start a New Journal",
    cyber: "INITIALIZE_UPLINK",
    terminal: "WIZARD: NEW_NODE",
    ronin: "ESTABLISH TERRITORY",
  },
  site_name_label: {
    default: "Name",
    sakura: "なまえ",
    octane: "Chassis Name",
    journal: "Journal Title",
    cyber: "SIGNAL_IDENTIFIER",
    terminal: "NAME:",
    ronin: "DOMAIN NAME",
  },
  site_name_placeholder: {
    default: "E.g. My Publication",
    sakura: "例：私の秘密基地",
    octane: "E.G. THE OCTANE LAB",
    journal: "E.g. My Writing Journey",
    cyber: "E.G._SIGNAL_NODE_01",
    terminal: "ENTER_NAME",
    ronin: "E.G. THE SHADOW PATH",
  },
  site_handle_label: {
    default: "Handle",
    sakura: "ユーザー名",
    octane: "Frequency",
    journal: "Journal URL",
    cyber: "UPLINK_FREQUENCY",
    terminal: "MOUNT_POINT:",
    ronin: "COORDINATES",
  },
  site_handle_desc: {
    default: "You can map a custom domain later.",
    sakura: "カスタムドメインは後で設定可能です。",
    octane: "You can map a custom domain later.",
    journal: "You can map a custom domain later.",
    cyber: "CRYPTO_DNS_OVERRIDE AVAILABLE LATER.",
    terminal: "# DNS_MAP_PENDING",
    ronin: "THE_PATH_CAN_BE_RENAMED_LATER",
  },
  available: {
    default: "Available",
    sakura: "利用可能",
    octane: "Cleared",
    journal: "Available",
    cyber: "FREQUENCY_CLEAR",
    terminal: "[OK]",
    ronin: "OPEN",
  },
  in_use: {
    default: "In Use",
    sakura: "使用中",
    octane: "Frequency Conflict",
    journal: "In Use",
    cyber: "SIGNAL_COLLISION",
    terminal: "[ERROR]",
    ronin: "TAKEN",
  },
  retreat: {
    default: "Cancel",
    sakura: "キャンセル",
    octane: "Abort",
    journal: "Cancel",
    cyber: "ABORT_MISSION",
    terminal: "[ ABORT ]",
    ronin: "RETREAT",
  },
  site_created_success: {
    default: "Publication created successfully!",
    sakura: "配信が正常に作成されました！",
    octane: "Site created successfully!",
    journal: "Journal started.",
    cyber: "UPLINK_ESTABLISHED.",
    terminal: "SUCCESS: NODE_CREATED",
    ronin: "TERRITORY ESTABLISHED.",
  },
  logo_uploaded_success: {
    default: "Logo uploaded!",
    sakura: "ロゴをアップロードしました",
    octane: "Emblem captured!",
    journal: "Icon updated.",
    cyber: "METADATA_EMBLEM_CAPTURED.",
    terminal: "IO: EMBLEM_UPLOADED",
    ronin: "BANNER EMBLEM CAPTURED.",
  },
  editor_back: {
    default: "Back",
    cyber: "RETURN_TO_BASE",
    terminal: "$ cd ..",
    techie: "INDEX_PROTOCOL",
    ronin: "退却 (Retreat)",
    sakura: "戻る",
  },
  editor_title_placeholder: {
    default: "Title",
    cyber: "SIGNAL_IDENT",
    terminal: "TITLE:",
    techie: "Title",
    journal: "Volume...",
    sakura: "タイトル",
    ronin: "伝説の題名",
    octane: "Title",
    classic: "Title",
    "classic-white": "Title",
    professional: "Document Title",
  },
  editor_content_placeholder: {
    default: "Start writing...",
    cyber: "COMMENCE_UPLINK...",
    terminal: "-- INSERT MODE --",
    techie: "INIT::DATA_STREAM",
    journal: "Wait for the ink to dry, then begin...",
    sakura: "ここから物語が始まる...",
    ronin: "影の言葉を刻む...",
    octane: "Rev Up Your Engine...",
    classic: "Start writing...",
    "classic-white": "Start writing...",
    professional: "Begin your transcription...",
  },
  editor_sync_synced: {
    default: "Synced",
    cyber: "SIGNAL_SYNCED",
    terminal: "SYNC_OK",
    techie: "DB_SYNC_OK",
    sakura: "同期済み",
    journal: "Entries Synced",
    ronin: "刻印完了 (Synced)",
    octane: "DATA_LOCKED",
    classic: "Synced",
    "classic-white": "Synced",
    professional: "Records Synced",
  },
  editor_sync_saving: {
    default: "Saving...",
    cyber: "BUFFER_UPLINK...",
    terminal: "WRITING...",
    techie: "COMMIT_IN_PROGRESS...",
    sakura: "保存中...",
    journal: "Recording...",
    ronin: "保存中 (Saving)",
    octane: "UPLOADING_SPECS",
    classic: "Saving...",
    "classic-white": "Saving...",
    professional: "Processing...",
  },
  editor_sync_not_synced: {
    default: "Not synced",
    cyber: "SIGNAL_LOST",
    terminal: "NOT SYNCED",
    techie: "NOT SYNCED",
    sakura: "未同期",
    journal: "Draft Mode",
    ronin: "未保存 (Not Synced)",
    octane: "SIGNAL_OPEN",
    classic: "Not synced",
    "classic-white": "Not synced",
    professional: "Changes pending",
  },
  change_avatar: {
    default: "Change Avatar",
    cyber: "UPDATE_BIOS_AVATAR",
    sakura: "写真を変更",
    octane: "Specs Image",
    journal: "Update Sketch",
    terminal: "CH_AVATAR",
    ronin: "CHANGE_VISAGE",
    techie: "UPDATE_AVATAR",
    classic: "Change Photo",
    "classic-white": "Update Image",
    professional: "Modify Identity",
  },
  save_changes: {
    default: "Save Changes",
    cyber: "COMMIT_SYNC",
    sakura: "変更を保存",
    octane: "Hard Save",
    journal: "Inscribe Changes",
    terminal: ":wq",
    ronin: "COMMIT_SEAL",
    techie: "COMMIT_CHANGES",
    classic: "Save",
    "classic-white": "Save Changes",
    professional: "Apply Changes",
  },
  social_networks: {
    default: "Social Networks",
    cyber: "SOCIAL_GRID_NODES",
    sakura: "SNS リンク",
    octane: "Freq Links",
    journal: "Correspondences",
    terminal: "SOCIALS",
    ronin: "ALLIANCE_NET",
    techie: "EXT_LINKS",
  },
  account_security: {
    default: "Account Security",
    cyber: "AUTH_PROTOCOLS",
    sakura: "アカウントの安全性",
    octane: "Encryption Level",
    journal: "Vault Access",
    terminal: "AUTH_CFG",
    ronin: "SHIELD_MANTRAS",
    techie: "SECURITY_PROTOCOLS",
  },
  display_name: {
    default: "Display Name",
    cyber: "SIGNAL_IDENT",
    sakura: "表示名",
    octane: "Pilot Handle",
    journal: "Pen Name",
    terminal: "UID_NAME",
    ronin: "TITLE",
    techie: "IDENT_NAME",
  },
  tagline: {
    default: "Tagline",
    cyber: "FREQ_TAG",
    sakura: "一言メッセージ",
    octane: "Engine Spec",
    journal: "Subtitle",
    terminal: "TAG_LINE",
    ronin: "BATTLE_CRY",
    techie: "SIGNAL_TAG",
  },
  location: {
    default: "Location",
    cyber: "LOC_REGION",
    sakura: "所在地",
    octane: "Garage Base",
    journal: "Abode",
    terminal: "TZ_LOC",
    ronin: "PROVINCE",
    techie: "LOC_COORDS",
  },
  bio: {
    default: "Bio",
    cyber: "IDENT_MANIFESTO",
    sakura: "自己紹介",
    octane: "Tech Specs",
    journal: "Author Biography",
    terminal: "USER_BIO",
    ronin: "WARRIOR_ORIGIN",
    techie: "CORE_TRANSCRIPTS",
  },
  profile_updated: {
    default: "Profile updated successfully!",
    cyber: "PROFILE_SYNCED_OK",
    sakura: "プロフィールを更新しました！",
    techie: "USER_RECORD_UPDATED",
    classic: "Profile updated",
    ronin: "SHINOBI_RECORD_SYNCED",
    octane: "SPECS_UPDATED",
    journal: "Chronicle Updated",
    professional: "Identity record synchronized",
  },
  settings_saved: {
    default: "Settings saved!",
    cyber: "SYSTEM_CONFIG_WRITTEN",
    sakura: "設定を保存しました",
    techie: "CONFIG_SAVED",
    classic: "Changes saved",
    ronin: "DOJO_LAWS_COMMITTED",
    octane: "SYSTEM_STABLE",
    journal: "Preferences Saved",
    professional: "System configuration updated",
  },
  profile_desc_long: {
    default: "Update your author biography and social correspondence.",
    cyber: "Update identifier metadata and encrypted social hooks.",
    sakura: "身元とソーシャルリンクを更新します。",
    techie: "REWRITE_USER_MANIFESTO_&_NODE_STREAMS",
    ronin: "REWRITE_YOUR_LEGEND_AND_ALLIANCES",
    octane: "RECALIBRATE_PILOT_SPECS_AND_TELEMETRY",
    journal: "Refine your author biography and archives.",
    professional: "Manage shared identity metadata and social integrations.",
  },
  email_label: {
    default: "Email Address",
    cyber: "UPLINK_COMM_ADDR",
    sakura: "メールアドレス",
    techie: "IDENT_EMAIL",
    ronin: "CONTACT_SCROLL",
    octane: "Comm Freq",
    journal: "Correspondence Address",
    terminal: "USER_EMAIL",
  },
  security_locked: {
    default: "Security settings are currently read-only.",
    cyber: "[SECURITY_MODULE_LOCKED]",
    sakura: "セキュリティ設定は読み取り専用です",
    techie: "SYS::SECURITY_MODULE::LOCKED - PREVENTING_UNAUTHORIZED_OVERRIDE",
    ronin: "SHIELD_MANTRA_LOCKED",
    octane: "VAULT_SEALED",
    journal: "Security preferences are currently managed by the editorial board.",
    terminal: "AUTH_LOCK: READ_ONLY",
  },
  account_desc_long: {
    default: "Update login credentials and security settings.",
    cyber: "Modify AUTH_KEYS and firewall parameters.",
    sakura: "ログイン情報とセキュリティ設定を更新します。",
    techie: "SECURITY_CREDENTIALS_&_PROTOCOL_OVERRIDE",
    ronin: "STRENGTHEN_SANCTUARY_MEMBRANE",
    octane: "HARDEN_AUTHENTICATION_BARRIER",
    journal: "Secure your vault and literary access.",
    professional: "Modify authentication architecture and security protocols.",
  },
  table_title: {
    default: "Title",
    sakura: "Title (タイトル)",
    ronin: "Title (題名)",
    octane: "Title",
    journal: "Title",
    cyber: "TITLE_KEY",
    terminal: "TITLE",
    techie: "TITLE",
  },
  table_status: {
    default: "Status",
    sakura: "Status (状態)",
    ronin: "Status (状態)",
    octane: "Status",
    journal: "Status",
    cyber: "STATUS_CODE",
    terminal: "STATUS",
    techie: "STATUS",
  },
  table_stats: {
    default: "Stats",
    sakura: "Stats (統計)",
    ronin: "Stats (統計)",
    octane: "Stats",
    journal: "Stats",
    cyber: "METRICS",
    terminal: "STATS",
    techie: "STATS",
  },
  table_date: {
    default: "Date",
    sakura: "Date (日付)",
    ronin: "Date (日付)",
    octane: "Date",
    journal: "Date",
    cyber: "TIMESTAMP",
    terminal: "DATE",
    techie: "DATE",
  },
  table_actions: {
    default: "Actions",
    sakura: "Actions (操作)",
    ronin: "Actions (操作)",
    octane: "Actions",
    journal: "Actions",
    cyber: "EXECUTE",
    terminal: "CMD",
    techie: "ACTIONS",
  },
  status_published: {
    default: "Published",
    sakura: "Published (公開中)",
    ronin: "現 (Active)",
    octane: "LIVE",
    journal: "Published",
    cyber: "PUBLISHED",
    terminal: "PUBLISHED",
    techie: "PUBLISHED",
  },
  status_draft: {
    default: "Draft",
    sakura: "Draft (下書き)",
    ronin: "潜 (Dormant)",
    octane: "DRAFT",
    journal: "Draft",
    cyber: "DRAFT",
    terminal: "DRAFT",
    techie: "DRAFT",
  },
  status_dormant: {
    default: "Dormant",
    sakura: "Dormant",
    ronin: "潜 (Dormant)",
    octane: "DORMANT",
    journal: "Dormant",
    cyber: "DORMANT",
    terminal: "DORMANT",
    techie: "DORMANT",
  },
  stats_views: {
    default: "Views",
    sakura: "Views (閲覧)",
    ronin: "目 (Views)",
    octane: "Hits",
    journal: "Views",
    cyber: "VIEWS",
    terminal: "VIEWS",
    techie: "VIEWS",
  },
  stats_total_views: {
    default: "Total Views",
    sakura: "総閲覧数",
    ronin: "総観 (Total Views)",
    octane: "Total Hits",
    journal: "Total Reads",
    cyber: "TOTAL_VIEWS",
    terminal: "TOTAL_VIEWS",
    techie: "TOTAL_VIEWS",
  },
  stats_30_days: {
    default: "Last 30 Days",
    sakura: "過去30日間",
    ronin: "三十日 (30 Days)",
    octane: "30-Day Trajectory",
    journal: "Past Month",
    cyber: "T-30 DAY LOG",
    terminal: "LAST_30_DAYS",
    techie: "T-30 DAYS",
  },
  stats_7_days: {
    default: "Last 7 Days",
    sakura: "過去7日間",
    ronin: "七日 (7 Days)",
    octane: "Weekly Revs",
    journal: "Past Week",
    cyber: "T-7 DAY LOG",
    terminal: "LAST_7_DAYS",
    techie: "T-7 DAYS",
  },
  stats_engagement: {
    default: "Engagement Rate",
    sakura: "エンゲージメント率",
    ronin: "絆 (Engagement)",
    octane: "Traction",
    journal: "Reader connection",
    cyber: "SIGNAL_LOCK",
    terminal: "ENGAGEMENT",
    techie: "ENGAGEMENT",
  },
  publication_updated_success: {
    default: "Publication updated!",
    octane: "Specs Updated!",
    cyber: "METADATA_SYNC_COMPLETE.",
    terminal: "SUCCESS: CONFIG_UPDATED",
    techie: "NODE_RECORD_SAVED",
    journal: "Journal Updated",
    sakura: "配信を更新しました！",
    ronin: "RECORD_SYNCED.",
  },
  input_active_status: {
    default: "",
    cyber: "[INPUT_ACTIVE]",
    terminal: "[ACTIVE]",
    techie: "[READY]",
  },
};

export function getStudioLabel(key: StudioLabelKey, theme: ThemeId): string {
  const themeLabels = STUDIO_LABELS[key];
  if (!themeLabels) return key;
  return themeLabels[theme] || themeLabels.default || key;
}

