services:
  conduit-web:
    container_name: conduit-web
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_DEFAULT_TENANT_ID=${NEXT_PUBLIC_DEFAULT_TENANT_ID}
        - NEXT_PUBLIC_STORAGE_URL=${NEXT_PUBLIC_STORAGE_URL}
        - NEXT_PUBLIC_BASE_DOMAIN=${NEXT_PUBLIC_BASE_DOMAIN}
        - NEXT_PUBLIC_PWA_VERSION=${NEXT_PUBLIC_PWA_VERSION}
    networks:
      - octane-net
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_DEFAULT_TENANT_ID
      - NEXT_PUBLIC_STORAGE_URL
      - NEXT_PUBLIC_BASE_DOMAIN
      - NEXT_PUBLIC_PWA_VERSION
      - CONDUIT_INTERNAL_API_URL

networks:
  octane-net:
    external: true
