import { ThemeVariant } from "./types";

export type LabelKey =
  | "home"
  | "library"
  | "activeSession"
  | "profile"
  | "mySites"
  | "forYou"
  | "following"
  | "login"
  | "dashboardTitle"
  | "dashboardSubtitle"
  | "createBlog"
  | "yourBlogs"
  | "editor"
  | "studio"
  | "loadMore"
  | "loading"
  | "noData"
  | "trending"
  | "draft"
  | "memberSince"
  | "writesAt"
  | "recentActivity"
  | "manage"
  | "noTransmissions"
  | "loadingProfile"
  | "visit"
  | "newStory"
  | "preview"
  | "saveDraft"
  | "publish"
  | "saving"
  | "synced"
  | "notSynced"
  | "enterTitle"
  | "search"
  | "recommended"
  | "signalSources"
  | "noTags"
  | "noUsers"
  | "settings"
  | "profileUpdated"
  | "settingsSaved"
  | "saveFailed"
  | "publicProfile"
  | "profileTab"
  | "accountTab"
  | "studioConsole"
  | "changeAvatar"
  | "saveChanges"
  | "socialNetworks"
  | "accountSecurity"
  | "newPost"
  | "analytics"
  | "perfVisualization"
  | "performances"
  | "transmissions"
  | "transmissionsSubtitle"
  | "statusPublished"
  | "statusDrafts"
  | "statusScheduled"
  | "statusUnlisted"
  | "statusDeleted"
  | "noDataDesc"
  | "storyUpdated"
  | "storyPublished"
  | "addTagWarning"
  | "addTagWarningSchedule"
  | "writeError"
  | "signOut"
  | "signIn"
  | "signUp"
  | "changeCover"
  | "photoByOnUnsplash"
  | "uploadTab"
  | "unsplashTab"
  | "dropImageHere"
  | "supportedFormats"
  | "selectFile"
  | "addFromDevice"
  | "addFromUnsplash"
  | "reply"
  | "comment"
  | "replyingTo"
  | "inputThoughts"
  | "noTransmissionsYet"
  | "awaitingSignal"
  | "syncing"
  | "saved"
  | "receivingTransmission"
  | "failure"
  | "scheduled"
  | "published"
  | "articleTitlePlaceholder"
  | "addTags"
  | "broadcastFailure"
  | "collapseSection"
  | "expandSection"
  | "newSearch"
  | "searchResults"
  | "waitingForSignal"
  | "searchingDatabase"
  | "postsTab"
  | "publicationsTab"
  | "peopleTab"
  | "followAction"
  | "followingAction"
  | "noStoriesFound"
  | "noNodesFound"
  | "noFrequenciesFound"
  | "accessAllFromAuthor"
  | "noBio"
  | "editProfileButton"
  | "followButton"
  | "unfollowButton"
  | "followersLabel"
  | "followingLabel"
  | "proLabel"
  | "uidLabel";

const labelMap: Record<LabelKey, Record<ThemeVariant | "default", string>> = {
  newSearch: {
    cyber: "NEW_SEARCH",
    sakura: "New Search (新しい検索)",
    ronin: "Seek New Path",
    octane: "NEW_SEARCH",
    journal: "New Search",
    terminal: "INIT_SEARCH_SEQUENCE",
    classic: "New Search",
    "classic-white": "New Search",
    professional: "New Search",
    techie: "INIT_QUERY",
    default: "New Search",
  },
  searchResults: {
    cyber: "SEARCH_RESULTS",
    sakura: "Search Results (検索結果)",
    ronin: "Findings (発見)",
    octane: "RESULTS",
    journal: "Search Results",
    terminal: "GREP_RESULTS",
    classic: "Search Results",
    "classic-white": "Search Results",
    professional: "Search Results",
    techie: "Query",
    default: "Search",
  },
  waitingForSignal: {
    cyber: "AWAITING_SIGNAL...",
    sakura: "信号を待っています...",
    ronin: "Waiting for path... (道を待つ)",
    octane: "AWAITING_SIGNAL...",
    journal: "Awaiting entry...",
    terminal: "waiting_for_stdin...",
    classic: "Waiting for search signal...",
    "classic-white": "Waiting for search signal...",
    professional: "Waiting for search signal...",
    techie: "AWAITING_INPUT",
    default: "Waiting for search signal...",
  },
  searchingDatabase: {
    cyber: "SEARCHING_DATABASE...",
    sakura: "データベースを検索中...",
    ronin: "Searching records...",
    octane: "SEARCHING...",
    journal: "Searching...",
    terminal: "DB_SHARD_SCAN",
    classic: "Searching database...",
    "classic-white": "Searching...",
    professional: "Searching...",
    techie: "DB_QUERY_ACTIVE",
    default: "Searching...",
  },
  postsTab: {
    cyber: "POSTS",
    sakura: "投稿 (Posts)",
    ronin: "Chronicles (記)",
    octane: "MODELS",
    journal: "Entries",
    terminal: "--posts",
    classic: "Posts",
    "classic-white": "Posts",
    professional: "Posts",
    techie: "BLOB_DATA",
    default: "Posts",
  },
  publicationsTab: {
    cyber: "NODES",
    sakura: "出版物 (Pubs)",
    ronin: "Territories (領)",
    octane: "FLEETS",
    journal: "Archives",
    terminal: "--nodes",
    classic: "Publications",
    "classic-white": "Publications",
    professional: "Publications",
    techie: "MODULE_EXPORTS",
    default: "Publications",
  },
  peopleTab: {
    cyber: "USERS",
    sakura: "ユーザー (People)",
    ronin: "Allies (友)",
    octane: "DRIVERS",
    journal: "Authors",
    terminal: "--users",
    classic: "People",
    "classic-white": "People",
    professional: "People",
    techie: "SYS_USERS",
    default: "People",
  },
  followAction: {
    cyber: "LINK",
    sakura: "Follow",
    ronin: "Pledge",
    octane: "Follow",
    journal: "Follow",
    terminal: "JOIN",
    classic: "Follow",
    "classic-white": "Follow",
    professional: "Follow",
    techie: "LINK",
    default: "Follow",
  },
  followingAction: {
    cyber: "LINKED",
    sakura: "Following",
    ronin: "Allied",
    octane: "Following",
    journal: "Following",
    terminal: "MEMBER",
    classic: "Following",
    "classic-white": "Following",
    professional: "Following",
    techie: "LINKED",
    default: "Following",
  },
  noStoriesFound: {
    cyber: "NO_TRANSMISSIONS_MATCHED",
    sakura: "投稿が見つかりませんでした (No stories found)",
    ronin: "The path is empty.",
    octane: "NO_MODELS_FOUND",
    journal: "No entries found matching your search.",
    terminal: "grep: no matches found",
    classic: "No stories found matching your search.",
    "classic-white": "No stories found",
    professional: "No stories found",
    techie: "NULL_DATA_SET",
    default: "No stories found",
  },
  noNodesFound: {
    cyber: "NO_PEERS_IDENTIFIED",
    sakura: "ユーザーが見つかりませんでした",
    ronin: "No allies identified.",
    octane: "NO_DRIVERS_FOUND",
    journal: "No authors identified.",
    terminal: "grep: /etc/passwd: identity not found",
    classic: "No users identified.",
    "classic-white": "No users found",
    professional: "No users identified.",
    techie: "PEER_NOT_FOUND",
    default: "No users identified.",
  },
  noFrequenciesFound: {
    cyber: "NO_FREQUENCIES_MATCHED",
    sakura: "周波数が一致しませんでした",
    ronin: "No frequencies found.",
    octane: "NO_FLEETS_FOUND",
    journal: "No archives found.",
    terminal: "grep: /dev/null: no output",
    classic: "No frequencies identified.",
    "classic-white": "No publications found",
    professional: "No publications found",
    techie: "MODULE_NOT_FOUND",
    default: "No frequencies identified.",
  },
  home: {
    cyber: "HOME",
    sakura: "Home",
    ronin: "Home",
    octane: "Garage",
    journal: "Journal",
    terminal: "~/home",
    classic: "Home",
    "classic-white": "Home",
    professional: "Home",
    techie: "Home",
    default: "Home",
  },
  library: {
    cyber: "Assets",
    sakura: "ライブラリ",
    ronin: "Library",
    octane: "Library",
    journal: "Library",
    terminal: "~/directory",
    techie: "Assets",
    classic: "Library",
    "classic-white": "Library",
    professional: "Library",
    default: "Library",
  },
  syncing: {
    cyber: "SYNCING_DATA...",
    sakura: "同期中...",
    ronin: "Saving...",
    octane: "SYNCING...",
    journal: "Syncing...",
    terminal: "SYNCING...",
    techie: "METADATA_SYNC",
    classic: "Syncing...",
    "classic-white": "Syncing...",
    professional: "Syncing...",
    default: "Syncing...",
  },
  saved: {
    cyber: "DATA_STABLE",
    sakura: "保存済み",
    ronin: "Chronicle saved",
    octane: "STABLE",
    journal: "Saved",
    terminal: "DATA_STABLE",
    techie: "RECORD_STABLE",
    classic: "Saved",
    "classic-white": "Saved",
    professional: "Saved",
    default: "Saved",
  },
  receivingTransmission: {
    cyber: "RECEIVING_TRANSMISSION...",
    sakura: "受信中...",
    ronin: "Entering...",
    octane: "RECEIVING...",
    journal: "Opening parchment...",
    terminal: "RX_DAT...",
    techie: "DOWNLOAD_INIT",
    classic: "Loading...",
    "classic-white": "Loading...",
    professional: "Loading...",
    default: "Receiving transmission...",
  },
  failure: {
    cyber: "FAILURE",
    sakura: "失敗",
    ronin: "Error",
    octane: "ERROR",
    journal: "Failure",
    terminal: "FAILURE",
    techie: "SIG_FAILURE",
    classic: "Failure",
    "classic-white": "Failure",
    professional: "Failure",
    default: "Failure",
  },
  articleTitlePlaceholder: {
    cyber: "TRANSMISSION_TITLE...",
    sakura: "タイトルを入力...",
    ronin: "Chronicle title...",
    octane: "Title...",
    journal: "Article title...",
    terminal: "TITLE...",
    techie: "RECORD_NAME",
    classic: "Article title...",
    "classic-white": "Article title...",
    professional: "Article title...",
    default: "Article Title...",
  },
  addTags: {
    cyber: "ADD_METADATA",
    sakura: "タグを追加",
    ronin: "Mark (印)",
    octane: "Add Tags",
    journal: "Add tags",
    terminal: "ADD_MARKERS",
    techie: "INS_METADATA",
    classic: "Add Tags",
    "classic-white": "Add Tags",
    professional: "Add Tags",
    default: "Add Tags",
  },
  broadcastFailure: {
    cyber: "BROADCAST_FAILURE",
    sakura: "放送事故が発生しました",
    ronin: "Establish failed",
    octane: "BROADCAST_ERROR",
    journal: "Publish failed",
    terminal: "SIG_FAILURE",
    techie: "SYNC_FAILURE",
    classic: "Publish failed",
    "classic-white": "Publish failed",
    professional: "Publish failed",
    default: "Critical failure during broadcast.",
  },
  activeSession: {
    cyber: "OS_KERNEL_LOGGED_IN",
    sakura: "アクティブなセッション",
    ronin: "Authenticated (認証)",
    octane: "ACTIVE_SESSION",
    journal: "Active session",
    terminal: "LOGGED_IN",
    techie: "SYS_SESSION_ACTIVE",
    classic: "Authenticated Session",
    "classic-white": "Authenticated Session",
    professional: "Authenticated Session",
    default: "Authenticated Session",
  },
  profile: {
    cyber: "PROFILE",
    sakura: "プロフィール",
    ronin: "Profile",
    octane: "PROFILE",
    journal: "Profile",
    terminal: "User",
    techie: "Config",
    classic: "Profile",
    "classic-white": "Profile",
    professional: "Profile",
    default: "Profile",
  },
  mySites: {
    cyber: "Stations",
    sakura: "Stories",
    ronin: "Domains",
    octane: "Dashboard",
    journal: "Notebook",
    terminal: "~/nodes",
    classic: "Sites",
    "classic-white": "Sites",
    professional: "Dashboard",
    techie: "Projects",
    default: "Sites",
  },
  forYou: {
    cyber: "FOR_YOU",
    sakura: "For You",
    ronin: "Chosen",
    octane: "Picks",
    journal: "Featured",
    terminal: ">> src_main",
    classic: "For You",
    "classic-white": "For You",
    professional: "For You",
    techie: "Primary Feed",
    default: "For You",
  },
  following: {
    cyber: "FOLLOWING",
    sakura: "Following",
    ronin: "Allies",
    octane: "Feed",
    journal: "Subscribed",
    terminal: ">> src_subs",
    classic: "Following",
    "classic-white": "Following",
    professional: "Following",
    techie: "Subscribed Signals",
    default: "Following",
  },
  login: {
    cyber: "LOGIN",
    sakura: "Login",
    ronin: "Enter",
    octane: "Login",
    journal: "Login",
    terminal: "./login",
    classic: "Login",
    "classic-white": "Login",
    professional: "Login",
    techie: "Auth",
    default: "Login",
  },

  dashboardTitle: {
    cyber: "Build your community",
    sakura: "Build Community",
    ronin: "Forge your legacy",
    octane: "Build your community",
    journal: "Your Writing Space",
    terminal: "CONDUIT_KERNEL // CORE",
    classic: "Build your community",
    "classic-white": "Build your community",
    professional: "Build your community",
    techie: "INITIALIZE_PROJECT",
    default: "Build your community",
  },
  dashboardSubtitle: {
    cyber: "NODE_STATUS: READY_FOR_UPLINK",
    sakura: "Your signal is ready. (信号発信の準備が整いました。)",
    ronin: "The path is open. (道は開かれた)",
    octane: "NODE_STATUS: ONLINE",
    journal: "Your notebook awaits.",
    terminal: "[SYS_OK] KERNEL_ROOT // UPLINK_ACTIVE",
    classic: "Your digital home awaits.",
    "classic-white": "Your digital home awaits.",
    professional: "Your digital home awaits.",
    techie: "System Ready. Awaiting Input.",
    default: "Your digital home awaits.",
  },
  createBlog: {
    cyber: "Initialize Transmission",
    sakura: "Create Blog (新しい発信地を作成)",
    ronin: "Establish Territory (領地を確立)",
    octane: "Initialize Transmission",
    journal: "Start a New Journal",
    terminal: "CREATE_NODE",
    classic: "Create Blog",
    "classic-white": "Create Blog",
    professional: "Create Blog",
    techie: "New Project",
    default: "Create Blog",
  },
  yourBlogs: {
    cyber: "RELAY_STATIONS",
    sakura: "My Transmissions",
    ronin: "My Domains",
    octane: "TRANSMISSIONS",
    journal: "Your Journals",
    terminal: "MOUNTED_NODES",
    classic: "Your Publications",
    "classic-white": "Your Publications",
    professional: "Your Publications",
    techie: "Active Projects",
    default: "Your Publications",
  },
  editor: {
    cyber: "EDITOR",
    sakura: "Editor",
    ronin: "Editor (記す)",
    octane: "EDITOR",
    journal: "Editor",
    terminal: "EDITOR",
    classic: "Editor",
    "classic-white": "Editor",
    professional: "Editor",
    techie: "IDE",
    default: "Editor",
  },
  studio: {
    cyber: "STUDIO",
    sakura: "Studio",
    ronin: "Studio (道場)",
    octane: "STUDIO",
    journal: "Studio",
    terminal: "STUDIO",
    classic: "Studio",
    "classic-white": "Studio",
    professional: "Studio",
    techie: "Workbench",
    default: "Studio",
  },

  loadMore: {
    cyber: "LOAD_MORE_DATA",
    sakura: "もっと見る",
    ronin: "さらに表示 (Load More)",
    octane: "LOAD_MORE",
    journal: "Continue Reading...",
    terminal: "FETCH_NEXT_SECTOR",
    classic: "Load Older Posts",
    "classic-white": "Load More",
    professional: "Load More",
    techie: "LOAD_NEXT_BATCH",
    default: "Load More",
  },
  loading: {
    cyber: "LOADING...",
    sakura: "読み込み中...",
    ronin: "探索中... (Searching...)",
    octane: "LOADING...",
    journal: "Loading...",
    terminal: "FETCHING...",
    classic: "Loading...",
    "classic-white": "Loading...",
    professional: "Loading...",
    techie: "PROCESSING...",
    default: "Loading...",
  },
  noData: {
    cyber: "NO_DATA_FOUND_IN_SECTOR",
    sakura: "信号なし",
    ronin: "静寂 (Silence)",
    octane: "NO_DATA",
    journal: "No entries found",
    terminal: "[EMPTY_SECTOR]",
    classic: "No data",
    "classic-white": "No data",
    professional: "No data",
    techie: "NULL_RESPONSE",
    default: "No data",
  },
  trending: {
    cyber: "DISCOVER.TRENDING",
    sakura: "トレンドを発見",
    ronin: "流行 (Trending)",
    octane: "TRENDING",
    journal: "Featured Entries",
    terminal: "TRENDING_SECTORS",
    classic: "Trending Now",
    "classic-white": "Trending Now",
    professional: "Trending",
    techie: "HIGH_TRAFFIC",
    default: "Trending Now",
  },
  draft: {
    cyber: "DRAFT_PREVIEW_MODE // TRANSMISSION_NOT_LIVE",
    sakura: "下書きプレビューモード：まだ公開されていません",
    ronin: "Draft (下書き) // Not Public",
    octane: "DRAFT // NOT LIVE",
    journal: "Draft Manuscript — Not Published",
    terminal: "[DRAFT] FILE_NOT_COMMITTED",
    classic: "Draft Preview",
    "classic-white": "Draft Preview",
    professional: "Draft",
    techie: "UNCOMMITTED_CHANGE",
    default: "Draft Preview",
  },
  scheduled: {
    cyber: "SCHEDULED_UPLINK",
    sakura: "予約済み",
    ronin: "Cycle (周期)",
    octane: "Scheduled",
    journal: "Scheduled",
    terminal: "CRON_SET",
    techie: "TIMED_SYNC",
    classic: "Scheduled",
    "classic-white": "Scheduled",
    professional: "Scheduled",
    default: "Scheduled",
  },
  published: {
    cyber: "BROADCAST_LIVE",
    sakura: "公開中",
    ronin: "Established (立)",
    octane: "Published",
    journal: "Published",
    terminal: "SIGNAL_UP",
    techie: "PROD_RECORD",
    classic: "Published",
    "classic-white": "Published",
    professional: "Published",
    default: "Published",
  },

  memberSince: {
    cyber: "Member Since",
    sakura: "Member Since (登録日)",
    ronin: "Joined (加盟)",
    octane: "Member Since",
    journal: "Writing since",
    terminal: "UPTIME",
    classic: "Member Since",
    "classic-white": "Member Since",
    professional: "Member Since",
    techie: "UPTIME_START",
    default: "Member Since",
  },
  writesAt: {
    cyber: "RELAID_FROM",
    sakura: "Writes At",
    ronin: "Domains",
    octane: "BROADCASTS",
    journal: "Journals",
    terminal: "FILE_ROOT",
    classic: "Publications",
    "classic-white": "Publications",
    professional: "Publications",
    techie: "ORIGIN_NODES",
    default: "Publications",
  },
  recentActivity: {
    cyber: "RECENT_ACTIVITY",
    sakura: "Recent Activity (最近のアクティビティ)",
    ronin: "History (歴史)",
    octane: "RECENT_ACTIVITY",
    journal: "Recent Entries",
    terminal: "HISTORY_LOG",
    classic: "Recent Activity",
    "classic-white": "Recent Activity",
    professional: "Recent Activity",
    techie: "SYSTEM_LOGS",
    default: "Recent Activity",
  },
  manage: {
    cyber: "Manage transmissions",
    sakura: "Manage (配信を管理)",
    ronin: "Govern (支配)",
    octane: "Manage",
    journal: "Manage",
    terminal: "CONFIG",
    classic: "Manage",
    "classic-white": "Manage",
    professional: "Manage",
    techie: "CONFIGURE",
    default: "Manage",
  },
  noTransmissions: {
    cyber: "NO_TRANSMISSIONS_DETECTED",
    sakura: "配信が見つかりません。ノードを初期化してください。",
    ronin: "No territory found. Forge one.",
    octane: "NO_TRANSMISSIONS",
    journal: "No publications yet",
    terminal: "[NO_MOUNTS_DETECTED]",
    classic: "No publications",
    "classic-white": "No publications",
    professional: "No publications",
    techie: "NO_ACTIVE_PROJECTS",
    default: "No publications",
  },
  noBio: {
    cyber: "NO_BIODATA_FOUND",
    sakura: "No description available. (自己紹介なし)",
    ronin: "言葉不要 (No words necessary)",
    octane: "No specs on file.",
    journal: "No biography written yet.",
    terminal: "NO_DESC",
    techie: "SYS::BIO::UNDEFINED - MODULE DESCRIPTION MISSING",
    classic: "No description available.",
    "classic-white": "No description available.",
    professional: "No description available.",
    default: "No description available.",
  },
  editProfileButton: {
    cyber: "CONFIG_PROFILE",
    sakura: "Settings (プロフィール設定)",
    ronin: "武器庫 (Armory)",
    octane: "WORKSHOP",
    journal: "Edit Profile",
    terminal: "[EDIT_CONFIG]",
    techie: "SYS::EDIT_IDENT",
    classic: "Edit Identification",
    "classic-white": "Edit Settings",
    professional: "Edit Profile",
    default: "Settings",
  },
  followButton: {
    cyber: "LINK",
    sakura: "Follow",
    ronin: "Pledge",
    octane: "Follow",
    journal: "Follow",
    terminal: "JOIN",
    classic: "Follow",
    "classic-white": "Follow",
    professional: "Follow",
    techie: "LINK",
    default: "Follow",
  },
  unfollowButton: {
    cyber: "UNLINK",
    sakura: "Unfollow",
    ronin: "Sever",
    octane: "Unfollow",
    journal: "Unfollow",
    terminal: "PART",
    classic: "Unfollow",
    "classic-white": "Unfollow",
    professional: "Unfollow",
    techie: "UNLINK",
    default: "Unfollow",
  },
  followersLabel: {
    cyber: "FOLLOWERS",
    sakura: "Followers (フォロワー)",
    ronin: "衆 (Allies)",
    octane: "Followers",
    journal: "Readers",
    terminal: "followers",
    techie: "Followers",
    classic: "Followers",
    "classic-white": "Followers",
    professional: "Followers",
    default: "Followers",
  },
  followingLabel: {
    cyber: "FOLLOWING",
    sakura: "Following (フォロー中)",
    ronin: "絆 (Bonds)",
    octane: "Following",
    journal: "Following",
    terminal: "following",
    techie: "Following",
    classic: "Following",
    "classic-white": "Following",
    professional: "Following",
    default: "Following",
  },
  proLabel: {
    cyber: "PRO_OPERATOR",
    sakura: "Pro",
    ronin: "師 (Master)",
    octane: "MECHANIC",
    journal: "Author",
    terminal: "PRO_USER",
    techie: "CORE_SYSTEMS",
    classic: "COMMANDER",
    "classic-white": "Pro",
    professional: "Pro",
    default: "Pro",
  },
  uidLabel: {
    cyber: "UID",
    sakura: "UID",
    ronin: "UID",
    octane: "UID",
    journal: "UID",
    terminal: "UID",
    techie: "NODE_ID",
    classic: "UID",
    "classic-white": "UID",
    professional: "UID",
    default: "UID",
  },
  loadingProfile: {
    cyber: "LOADING_PROFILE...",
    sakura: "プロフィールを読み込み中...",
    ronin: "Searching Records...",
    octane: "LOADING...",
    journal: "Loading profile...",
    terminal: "FETCHING_USER_DATA...",
    classic: "Loading...",
    "classic-white": "Loading...",
    professional: "Loading...",
    techie: "FETCHING_USER_DATA...",
    default: "Loading...",
  },
  visit: {
    cyber: "Monitor frequency",
    sakura: "Visit (周波数)",
    ronin: "Enter (入る)",
    octane: "View",
    journal: "Visit",
    terminal: "CD_INTO",
    classic: "Visit",
    "classic-white": "Visit",
    professional: "Visit",
    techie: "ACCESS_NODE",
    default: "Visit",
  },

  newStory: {
    cyber: "NEW_SIGNAL",
    sakura: "New Story",
    ronin: "New Chronicle",
    octane: "New Blueprint",
    journal: "New Entry",
    terminal: "$ vim new.md",
    classic: "New Story",
    "classic-white": "New Story",
    professional: "New Post",
    techie: "INIT_NEW_FILE",
    default: "New Story",
  },
  preview: {
    cyber: "PREVIEW_SIGNAL",
    sakura: "プレビュー",
    ronin: "View (視)",
    octane: "Preview",
    journal: "Preview",
    terminal: "PEEK_DAT",
    classic: "Preview",
    "classic-white": "Preview",
    professional: "Preview",
    techie: "SIMULATE_ENV",
    default: "Preview",
  },
  saveDraft: {
    cyber: "DRAFT",
    sakura: "下書き",
    ronin: "下書き (Draft)",
    octane: "DRAFT",
    journal: "Draft",
    terminal: ":w",
    classic: "Draft",
    "classic-white": "Draft",
    professional: "Draft",
    techie: "STASH_CHANGES",
    default: "Draft",
  },
  publish: {
    cyber: "INIT_BROADCAST",
    sakura: "公開",
    ronin: "Establish (立)",
    octane: "Publish",
    journal: "Publish",
    terminal: "SIG_ON",
    techie: "PUSH_RECORD",
    classic: "Publish",
    "classic-white": "Publish",
    professional: "Publish",
    default: "Publish",
  },
  saving: {
    cyber: "SAVING...",
    sakura: "保存中...",
    ronin: "Saving...",
    octane: "SAVING...",
    journal: "Saving...",
    terminal: "SYNCING...",
    classic: "Saving...",
    "classic-white": "Saving...",
    professional: "Saving...",
    techie: "WRITING_TO_DISK...",
    default: "Saving...",
  },
  synced: {
    cyber: "SYNCED",
    sakura: "同期済み",
    ronin: "Synced",
    octane: "SYNCED",
    journal: "Saved",
    terminal: "SYNCED",
    classic: "Synced",
    "classic-white": "Synced",
    professional: "Synced",
    techie: "SYNC_COMPLETE",
    default: "Synced",
  },
  notSynced: {
    cyber: "NOT_SYNCED",
    sakura: "未同期",
    ronin: "Not synced",
    octane: "NOT_SYNCED",
    journal: "Not saved",
    terminal: "NOT SYNCED",
    classic: "Not synced",
    "classic-white": "Not synced",
    professional: "Not synced",
    techie: "SYNC_PENDING",
    default: "Not synced",
  },
  enterTitle: {
    cyber: "ENTER_TITLE...",
    sakura: "タイトルを入力...",
    ronin: "Enter title...",
    octane: "ENTER_TITLE...",
    journal: "Enter title...",
    terminal: "Enter title...",
    classic: "Enter title...",
    "classic-white": "Enter title...",
    professional: "Enter title...",
    techie: "DEFINE_HEADER...",
    default: "Enter title...",
  },

  search: {
    cyber: "SEARCH",
    sakura: "Search",
    ronin: "Seek",
    octane: "Search",
    journal: "Search",
    terminal: "Grep",
    classic: "Search",
    "classic-white": "Search",
    professional: "Search",
    techie: "Query",
    default: "Search",
  },
  recommended: {
    cyber: "Recommended",
    sakura: "Recommended (おすすめ)",
    ronin: "Chosen (選)",
    octane: "Topics",
    journal: "Topics",
    terminal: "man pages",
    classic: "Recommended",
    "classic-white": "Recommended",
    professional: "Recommended",
    techie: "OPTIMIZED_PATHS",
    default: "Recommended",
  },
  signalSources: {
    cyber: "Signal Sources",
    sakura: "Who to Follow (フォロー候補)",
    ronin: "Allies (絆)",
    octane: "Suggested",
    journal: "Notable Authors",
    terminal: "active_connections",
    classic: "Who to Follow",
    "classic-white": "Who to Follow",
    professional: "Suggested",
    techie: "PEER_NODES",
    default: "Who to Follow",
  },
  noTags: {
    cyber: "NO_ACTIVE_SOURCE_DETECTED",
    sakura: "No tags (タグなし)",
    ronin: "RECORD_NOT_FOUND",
    octane: "No tags yet",
    journal: "No topics yet",
    terminal: "[EMPTY_SECTOR]",
    classic: "No tags yet",
    "classic-white": "No tags yet",
    professional: "No tags yet",
    techie: "Null Response",
    default: "No tags yet",
  },
  noUsers: {
    cyber: "NO_SIGNALS_FOUND",
    sakura: "No users (ユーザーなし)",
    ronin: "No allies (仲間なし)",
    octane: "No users found",
    journal: "No authors found",
    terminal: "NO_ACTIVE_NODES",
    classic: "No users found",
    "classic-white": "No users found",
    professional: "No users found",
    techie: "NO_PEERS_FOUND",
    default: "No users found",
  },

  settings: {
    cyber: "SETTINGS",
    sakura: "環境設定",
    ronin: "環境設定 (Settings)",
    octane: "SETTINGS",
    journal: "Settings",
    terminal: "CONFIG",
    classic: "Settings",
    "classic-white": "Settings",
    professional: "Settings",
    techie: "SYSTEM_CONFIG",
    default: "Settings",
  },
  profileUpdated: {
    cyber: "Profile updated",
    sakura: "プロフィールを更新しました",
    ronin: "Profile updated",
    octane: "Profile updated",
    journal: "Profile updated",
    terminal: "PROFILE_SYNCED",
    classic: "Profile updated",
    "classic-white": "Profile updated",
    professional: "Profile updated",
    techie: "USER_RECORD_UPDATED",
    default: "Profile updated",
  },
  settingsSaved: {
    cyber: "Settings saved",
    sakura: "設定を保存しました",
    ronin: "Settings saved",
    octane: "Settings saved",
    journal: "Settings saved",
    terminal: "CONFIG_WRITTEN",
    classic: "Settings saved",
    "classic-white": "Settings saved",
    professional: "Settings saved",
    techie: "CONFIG_SAVED",
    default: "Settings saved",
  },
  saveFailed: {
    cyber: "Failed to save settings",
    sakura: "保存に失敗しました",
    ronin: "Failed to save",
    octane: "Save failed",
    journal: "Failed to save",
    terminal: "WRITE_ERROR",
    classic: "Failed to save",
    "classic-white": "Failed to save",
    professional: "Failed to save",
    techie: "WRITE_FAILURE",
    default: "Failed to save",
  },
  publicProfile: {
    cyber: "Public Profile",
    sakura: "公開プロフィール",
    ronin: "名 (Public Profile)",
    octane: "Public Profile",
    journal: "Public Profile",
    terminal: "PUBLIC_IDENTITY",
    classic: "Public Profile",
    "classic-white": "Public Profile",
    professional: "Public Profile",
    techie: "USER_IDENTITY",
    default: "Public Profile",
  },
  profileTab: {
    cyber: "Public Profile",
    sakura: "プロフィール",
    ronin: "名 (Public Profile)",
    octane: "Profile",
    journal: "Profile",
    terminal: "PROFILE",
    classic: "Public Profile",
    "classic-white": "Public Profile",
    professional: "Profile",
    techie: "USER_PROFILE",
    default: "Public Profile",
  },
  accountTab: {
    cyber: "Account",
    sakura: "アカウント",
    ronin: "文 (Account)",
    octane: "Account",
    journal: "Account",
    terminal: "ACCOUNT",
    classic: "Account",
    "classic-white": "Account",
    professional: "Account",
    techie: "ACCESS_CONTROL",
    default: "Account",
  },
  studioConsole: {
    cyber: "Studio Console",
    sakura: "スタジオ管理",
    ronin: "道場 (Studio Console)",
    octane: "Studio Console",
    journal: "Studio",
    terminal: "STUDIO_CLI",
    classic: "Studio Console",
    "classic-white": "Studio Console",
    professional: "Studio Console",
    techie: "ADMIN_CONSOLE",
    default: "Studio Console",
  },
  changeAvatar: {
    cyber: "CHANGE AVATAR",
    sakura: "写真を変更",
    ronin: "Change (変更)",
    octane: "Change Avatar",
    journal: "Change Photo",
    terminal: "CHANGE",
    classic: "Change Avatar",
    "classic-white": "Change Avatar",
    professional: "Change Avatar",
    techie: "UPDATE_AVATAR",
    default: "Change Avatar",
  },
  saveChanges: {
    cyber: "SAVE CHANGES",
    sakura: "変更を保存",
    ronin: "Save (保存)",
    octane: "Save Changes",
    journal: "Save Changes",
    terminal: ":wq",
    classic: "Save Changes",
    "classic-white": "Save Changes",
    professional: "Save Changes",
    techie: "COMMIT_CHANGES",
    default: "Save Changes",
  },
  socialNetworks: {
    cyber: "Social Networks",
    sakura: "SNS リンク",
    ronin: "絆 (Social Networks)",
    octane: "Social Links",
    journal: "Social Links",
    terminal: "SOCIALS",
    classic: "Social Networks",
    "classic-white": "Social Networks",
    professional: "Social Networks",
    techie: "EXT_LINKS",
    default: "Social Networks",
  },
  accountSecurity: {
    cyber: "Account Security",
    sakura: "アカウント設定",
    ronin: "文 (Account Security)",
    octane: "Account Security",
    journal: "Account Security",
    terminal: "AUTH_CONFIG",
    classic: "Account Security",
    "classic-white": "Account Security",
    professional: "Account Security",
    techie: "SECURITY_PROTOCOLS",
    default: "Account Security",
  },
  newPost: {
    cyber: "INIT_SIGNAL",
    sakura: "New Story",
    ronin: "New Chronicle",
    octane: "New Blueprint",
    journal: "New Entry",
    terminal: "touch post.md",
    classic: "New Post",
    "classic-white": "New Post",
    professional: "New Post",
    techie: "INIT_FILE",
    default: "New Post",
  },
  analytics: {
    cyber: "SIGNAL_ANALYTICS",
    sakura: "概況 (Analytics)",
    ronin: "兵法 (Analytics)",
    octane: "Stream Metrics",
    journal: "Writing Stats",
    terminal: "sys_stat",
    classic: "Analytics",
    "classic-white": "Analytics",
    professional: "Analytics",
    techie: "TELEMETRY",
    default: "Analytics",
  },
  perfVisualization: {
    cyber: "SIGNAL_VISUALIZATION",
    sakura: "パフォーマンス推移",
    ronin: "戦果 (Performance)",
    octane: "Signal Stream",
    journal: "Reading Patterns",
    terminal: "graph -v",
    classic: "Performance Visualization",
    "classic-white": "Performance Visualization",
    professional: "Performance Visualization",
    techie: "DATA_VIS",
    default: "Performance Visualization",
  },
  performances: {
    cyber: "THROUGHPUT",
    sakura: "Story Insights",
    ronin: "Chronicle Records",
    octane: "Lap Times",
    journal: "Reading History",
    terminal: "ls -la log",
    classic: "Performances",
    "classic-white": "Performances",
    professional: "Performances",
    techie: "METRICS",
    default: "Performances",
  },
  transmissions: {
    cyber: "SIGNALS",
    sakura: "Stories",
    ronin: "Chronicles",
    octane: "Blueprints",
    journal: "Entries",
    terminal: "ls -la files",
    classic: "Transmissions",
    "classic-white": "Transmissions",
    professional: "Transmissions",
    techie: "FILE_LIST",
    default: "Transmissions",
  },
  transmissionsSubtitle: {
    cyber: "ACTIVE_SIGNALS // INTERFACE_READY",
    sakura: "公開済みまたは下書きの記事を管理します。",
    ronin: "影の記録を管理する (Manage your shadow records)",
    octane: "Monitor and manage your active broadcasts and drafts",
    journal: "Manage your writings and drafts",
    terminal: "MANAGE_FILESYSTEM",
    classic: "Monitor and manage your active broadcasts and drafts",
    "classic-white": "Monitor and manage your active broadcasts and drafts",
    professional: "Monitor and manage your active broadcasts and drafts",
    techie: "MANAGE_FILESYSTEM",
    default: "Monitor and manage your active broadcasts and drafts",
  },
  statusPublished: {
    cyber: "PUBLISHED",
    sakura: "公開済み",
    ronin: "表 (Public)",
    octane: "On Air",
    journal: "Published",
    terminal: "CHMOD_+RX",
    classic: "Published",
    "classic-white": "Published",
    professional: "Published",
    techie: "PROD_RECORD",
    default: "Published",
  },
  statusDrafts: {
    cyber: "DRAFTS",
    sakura: "下書き",
    ronin: "裏 (Draft)",
    octane: "Preparing",
    journal: "Drafts",
    terminal: "TMP_FILE",
    classic: "Drafts",
    "classic-white": "Drafts",
    professional: "Drafts",
    techie: "LOCAL_FILES",
    default: "Drafts",
  },
  statusScheduled: {
    cyber: "SCHEDULED",
    sakura: "予約済み",
    ronin: "刻 (Scheduled)",
    octane: "Timer",
    journal: "Scheduled",
    terminal: "CRON_JOB",
    classic: "Scheduled",
    "classic-white": "Scheduled",
    professional: "Scheduled",
    techie: "TIMED_JOB",
    default: "Scheduled",
  },
  statusUnlisted: {
    cyber: "UNLISTED",
    sakura: "未登録",
    ronin: "隠 (Hidden)",
    octane: "Ghost Mode",
    journal: "Unlisted",
    terminal: "HIDDEN_BIT",
    classic: "Unlisted",
    "classic-white": "Unlisted",
    professional: "Unlisted",
    techie: "HIDDEN_FILES",
    default: "Unlisted",
  },
  statusDeleted: {
    cyber: "DELETED",
    sakura: "ゴミ箱",
    ronin: "消 (Erased)",
    octane: "Scrapped",
    journal: "Trash",
    terminal: "RM_RF",
    classic: "Deleted",
    "classic-white": "Deleted",
    professional: "Deleted",
    techie: "TRASH_BIN",
    default: "Deleted",
  },
  noDataDesc: {
    cyber: "EXPECTING_BROADCASTS // FREQUENCY_IDLE",
    sakura: "ここにはまだ何もありません。",
    ronin: "No territory found. Forge one.",
    octane: "Your transmissions will appear here once they are initiated.",
    journal: "Your collection is currently empty in this category.",
    terminal: "[NO_DATA_IN_SECTOR]",
    techie: "Awaiting source signal. Null metadata index.",
    classic: "Your transmissions will appear here once they are initiated.",
    "classic-white": "Your transmissions will appear here once they are initiated.",
    professional: "Your transmissions will appear here once they are initiated.",
    default: "Your transmissions will appear here once they are initiated.",
  },
  storyUpdated: {
    cyber: "TRANSMISSION_UPDATED",
    sakura: "記事を更新しました",
    ronin: "Chronicle updated",
    octane: "TRANSMISSION_UPDATED",
    journal: "Story updated",
    terminal: "FILE_WRITTEN",
    techie: "RECORD_UPDATED",
    classic: "Story updated",
    "classic-white": "Story updated",
    professional: "Story updated",
    default: "Story updated",
  },
  storyPublished: {
    cyber: "TRANSMISSION_BROADCASTED",
    sakura: "記事を公開しました🌸",
    ronin: "Chronicle established",
    octane: "BROADCAST_LIVE",
    journal: "Story published",
    terminal: "SIGNAL_LIVE",
    techie: "DEPLOY_COMPLETE",
    classic: "Post published",
    "classic-white": "Post published",
    professional: "Post published",
    default: "STORY PUBLISHED",
  },
  addTagWarning: {
    cyber: "ADD_METADATA_REQUIRED",
    sakura: "タグを少なくとも1つ設定してください。",
    ronin: "Marks required",
    octane: "TAG_REQUIRED",
    journal: "Please add a tag",
    terminal: "TAG_MISSING",
    techie: "METADATA_REQUIRED",
    classic: "Please add a tag",
    "classic-white": "Please add a tag",
    professional: "Please add a tag",
    default: "Please add at least one tag before publishing!",
  },
  addTagWarningSchedule: {
    cyber: "ADD_METADATA_REQUIRED",
    sakura: "タグを少なくとも1つ設定してください。",
    ronin: "Marks required",
    octane: "TAG_REQUIRED",
    journal: "Please add a tag",
    terminal: "TAG_MISSING",
    techie: "METADATA_REQUIRED",
    classic: "Please add a tag",
    "classic-white": "Please add a tag",
    professional: "Please add a tag",
    default: "Please add at least one tag before scheduling!",
  },
  writeError: {
    cyber: "WRITE_ERROR",
    sakura: "保存に失敗しました",
    ronin: "Forge failed",
    octane: "WRITE_ERROR",
    journal: "Save failed",
    terminal: "FS_ERR",
    techie: "IO_FAILURE",
    classic: "Save failed",
    "classic-white": "Save failed",
    professional: "Save failed",
    default: "Save failed",
  },
  signOut: {
    cyber: "DISCONNECT",
    sakura: "ログアウト",
    ronin: "Leave (去る)",
    octane: "Sign Out",
    journal: "Sign Out",
    terminal: "logout",
    techie: "TERM_SESSION",
    classic: "Sign out",
    "classic-white": "Sign out",
    professional: "Sign out",
    default: "Sign out",
  },
  signIn: {
    cyber: "AUTHENTICATE",
    sakura: "ログイン",
    ronin: "Enter (入る)",
    octane: "Sign In",
    journal: "Sign In",
    terminal: "login",
    techie: "AUTHENTICATE",
    classic: "Sign In",
    "classic-white": "Sign In",
    professional: "Sign In",
    default: "Sign In",
  },
  signUp: {
    cyber: "REGISTER_NODE",
    sakura: "新規登録",
    ronin: "Join (加盟)",
    octane: "Sign Up",
    journal: "Sign Up",
    terminal: "register",
    techie: "PROV_IDENTITY",
    classic: "Sign Up",
    "classic-white": "Sign Up",
    professional: "Sign Up",
    default: "Sign Up",
  },
  changeCover: {
    cyber: "CHANGE_IMAGE",
    sakura: "写真を変更",
    ronin: "Alter (変更)",
    octane: "Change Cover",
    journal: "Change Cover",
    terminal: "CHANGE_IMG",
    techie: "UPDATE_ASSET",
    classic: "Change",
    "classic-white": "Change",
    professional: "Change",
    default: "Change",
  },
  photoByOnUnsplash: {
    cyber: "Photo by {name} on Unsplash",
    sakura: "Photo by {name} on Unsplash",
    ronin: "Photo by {name} on Unsplash",
    octane: "Photo by {name} on Unsplash",
    journal: "Photo by {name} on Unsplash",
    terminal: "SRC: {name} (Unsplash)",
    techie: "ASSET_BY: {name} // UNSPLASH",
    classic: "Photo by {name} on Unsplash",
    "classic-white": "Photo by {name} on Unsplash",
    professional: "Photo by {name} on Unsplash",
    default: "Photo by {name} on Unsplash",
  },
  uploadTab: {
    cyber: "UPLOAD",
    sakura: "アップロード",
    ronin: "Import (輸入)",
    octane: "Upload",
    journal: "Upload",
    terminal: "FTP_PUSH",
    techie: "FS_UPLOAD",
    classic: "Upload",
    "classic-white": "Upload",
    professional: "Upload",
    default: "Upload",
  },
  unsplashTab: {
    cyber: "UNSPLASH",
    sakura: "Unsplash",
    ronin: "Seek (探)",
    octane: "Unsplash",
    journal: "Unsplash",
    terminal: "NET_FETCH",
    techie: "UNSPLASH_DB",
    classic: "Unsplash",
    "classic-white": "Unsplash",
    professional: "Unsplash",
    default: "Unsplash",
  },
  dropImageHere: {
    cyber: "DROP_IMAGE_HERE",
    sakura: "画像をここにドロップ",
    ronin: "Place image here",
    octane: "DROP_IMAGE",
    journal: "Drop image here",
    terminal: "DRAG_AND_DROP",
    techie: "DROP_ASSET_HERE",
    classic: "Drop image here",
    "classic-white": "Drop image here",
    professional: "Drop image here",
    default: "Drop image here or click to browse",
  },
  supportedFormats: {
    cyber: "JPG_PNG_WEBP_MAX_5MB",
    sakura: "JPG, PNG, WEBP (最大 5MB)",
    ronin: "JPG, PNG, WEBP (Max 5MB)",
    octane: "JPG, PNG, WEBP (Max 5MB)",
    journal: "JPG, PNG, WEBP (Max 5MB)",
    terminal: "IMG_TYPES: JPG, PNG, WEBP",
    techie: "SUPPORTED: JPG, PNG, WEBP (5MB)",
    classic: "Max 5MB",
    "classic-white": "Max 5MB",
    professional: "Max 5MB",
    default: "Supported: JPG, PNG, WEBP (Max 5MB)",
  },
  selectFile: {
    cyber: "SELECT_FILE",
    sakura: "ファイルを選択",
    ronin: "Select (選)",
    octane: "Select File",
    journal: "Select File",
    terminal: "SELECT",
    techie: "BROWSE_FILES",
    classic: "Select File",
    "classic-white": "Select File",
    professional: "Select File",
    default: "Select File",
  },
  addFromDevice: {
    cyber: "ADD_FROM_DEVICE",
    sakura: "デバイスから追加",
    ronin: "Add (追加)",
    octane: "ADD_FROM_DEVICE",
    journal: "Add from device",
    terminal: "ADD --LOCAL",
    techie: "IMPORT_LOCAL",
    classic: "Add from device",
    "classic-white": "Add from device",
    professional: "Add from device",
    default: "ADD IMAGE FROM DEVICE",
  },
  addFromUnsplash: {
    cyber: "ADD_FROM_UNSPLASH",
    sakura: "Unsplashから追加",
    ronin: "Seek (探)",
    octane: "ADD_FROM_UNSPLASH",
    journal: "Add from Unsplash",
    terminal: "ADD --REMOTE",
    techie: "FETCH_REMOTE",
    classic: "Add from Unsplash",
    "classic-white": "Add from Unsplash",
    professional: "Add from Unsplash",
    default: "ADD IMAGE FROM UNSPLASH",
  },
  reply: {
    cyber: "REPLY",
    sakura: "返信",
    ronin: "Answer (答える)",
    octane: "Reply",
    journal: "Reply",
    terminal: "REPLY",
    techie: "SEND_REP",
    classic: "Reply",
    "classic-white": "Reply",
    professional: "Reply",
    default: "Reply",
  },
  comment: {
    cyber: "COMMENT",
    sakura: "コメント",
    ronin: "Chronicle (言)",
    octane: "Comment",
    journal: "Comment",
    terminal: "LOG",
    techie: "ADD_LOG",
    classic: "Comment",
    "classic-white": "Comment",
    professional: "Comment",
    default: "Comments",
  },
  replyingTo: {
    cyber: "REPLYING_TO",
    sakura: "返信先：",
    ronin: "Replying to",
    octane: "Replying",
    journal: "Replying to",
    terminal: "REPLYING_TO",
    techie: "TARGETING",
    classic: "Replying to",
    "classic-white": "Replying to",
    professional: "Replying to",
    default: "Replying to",
  },
  inputThoughts: {
    cyber: "INPUT_DATA...",
    sakura: "あなたの考えを教えてください...",
    ronin: "Input thoughts...",
    octane: "INPUT_THOUGHTS...",
    journal: "Your thoughts...",
    terminal: "stdin...",
    techie: "INPUT_STREAM...",
    classic: "Input thoughts...",
    "classic-white": "Input thoughts...",
    professional: "Input thoughts...",
    default: "Input thoughts...",
  },
  noTransmissionsYet: {
    cyber: "NO_SIGNALS_DETECTED",
    sakura: "まだ送信履歴はありません。",
    ronin: "Silence (静寂)",
    octane: "NO_TRANSMISSIONS",
    journal: "No entries yet",
    terminal: "[EMPTY_SECTOR]",
    techie: "AWAITING_SIGNAL",
    classic: "No posts yet",
    "classic-white": "No posts yet",
    professional: "No posts yet",
    default: "No transmissions yet.",
  },
  awaitingSignal: {
    cyber: "AWAITING_SIGNAL_UPLINK...",
    sakura: "信号待機中...",
    ronin: "Awaiting...",
    octane: "AWAITING_SIGNAL...",
    journal: "Awaiting entry...",
    terminal: "AWAITING_DAT_INPUT...",
    techie: "IDLE_PROCESS...",
    classic: "Awaiting...",
    "classic-white": "Awaiting...",
    professional: "Awaiting...",
    default: "Awaiting signal broadcast...",
  },
  collapseSection: {
    cyber: "MINIMIZE_INTERFACE",
    sakura: "閉じる",
    ronin: "収 (Collapse)",
    octane: "MINIMIZE",
    journal: "Collapse",
    terminal: "COLLAPSE",
    techie: "MIN_VIEW",
    classic: "Collapse",
    "classic-white": "Collapse",
    professional: "Minimize",
    default: "Collapse Section",
  },
  expandSection: {
    cyber: "EXPAND_MATRIX",
    sakura: "開く",
    ronin: "拡 (Expand)",
    octane: "EXPAND",
    journal: "Expand",
    terminal: "EXPAND",
    techie: "EXP_VIEW",
    classic: "Expand",
    "classic-white": "Expand",
    professional: "Expand",
    default: "Expand Section",
  },
  accessAllFromAuthor: {
    cyber: "ACCESS_ALL_FREQUENCIES_FROM_{name}",
    sakura: "{name}の全投稿を見る",
    ronin: "{name}の全記録を閲覧",
    octane: "Access {name}'s garage",
    journal: "Review all entries by {name}",
    terminal: "ls /u/{name}",
    techie: "ACCESS_FULL_STREAM_FROM_{name}",
    classic: "Access all from {name}",
    "classic-white": "Access all posts from {name}",
    professional: "View all posts by {name}",
    default: "Access all posts from {name}",
  },
};

export function getLabel(key: LabelKey, theme: ThemeVariant): string {
  return labelMap[key]?.[theme] || labelMap[key]?.["default"] || key;
}

const japaneseSubLabels: Record<string, { sakura?: string; ronin?: string; journal?: string }> = {
  home: { sakura: "ホーム", ronin: "家", journal: "日誌" },
  library: { sakura: "保存", ronin: "蔵", journal: "文庫" },
  mySites: { sakura: "マイサイト", ronin: "城", journal: "工房" },
  forYou: { sakura: "おすすめ", ronin: "選", journal: "推奨" },
  following: { sakura: "フォロー中", ronin: "絆", journal: "閲読" },
  login: { sakura: "ログイン", ronin: "入", journal: "記帳" },
  profile: { ronin: "身分", journal: "著者" },
  settings: { ronin: "掟", journal: "設定" },
};

export function getJapaneseSubLabel(key: string, theme: ThemeVariant): string | undefined {
  if (theme === "sakura") return japaneseSubLabels[key]?.sakura;
  if (theme === "ronin") return japaneseSubLabels[key]?.ronin;
  if (theme === "journal") return japaneseSubLabels[key]?.journal;
  return undefined;
}
